#!/usr/bin/env bash
doctor|command.doctor.description|commands/doctor.sh
devices|command.devices.description|commands/devices.sh
connect|command.connect.description|commands/connect.sh
init|command.init.description|commands/init.sh
config|command.config.description|commands/config.sh
build|command.build.description|commands/build.sh
apk|command.apk.description|commands/apk.sh
release|command.release.description|commands/release.sh
install|command.install.description|commands/install.sh
self-update|command.self-update.description|commands/self-update.sh
launch|command.launch.description|commands/launch.sh
logcat|command.logcat.description|commands/logcat.sh
run|command.run.description|commands/run.sh
dev|command.dev.description|commands/dev.sh
clean|command.clean.description|commands/clean.sh
info|command.info.description|commands/info.sh
