org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.resvalues=false
android.defaults.buildfeatures.shaders=false
